# Generated by Django 2.0.1 on 2018-01-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headband',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headband_name', models.CharField(max_length=200)),
                ('shopify_id', models.CharField(max_length=200)),
            ],
        ),
    ]
