# Generated by Django 2.0.1 on 2018-01-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headband',
            name='image_path',
            field=models.FilePathField(default='/images/default.png'),
        ),
    ]
