# Generated by Django 2.0.1 on 2018-01-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_headband_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headband',
            name='image_path',
            field=models.ImageField(upload_to='resources/headbands'),
        ),
    ]
